monitor=,preferred,auto,1

exec-once = waybar
exec-once = kitty

input {
    kb_layout = us
}

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
}

decoration {
    rounding = 6
    blur = yes
}

animations {
    enabled = yes
}
